name: Deploy Resume to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - "apps/resume/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/deploy-resume.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build resume
        run: pnpm --filter resume build

      - name: Deploy to Cloudflare Pages
        run: pnpm --filter resume exec wrangler pages deploy ./dist --project-name=resume
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
